// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqdblqnkyvkjagzjbuvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxZGJscW5reXZramFnempidXZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MDI2MjEsImV4cCI6MjA1ODI3ODYyMX0.csAypaYZAb5p1sEGCgqGmupR98lNneQRN_3qM4ICwZY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);